<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC7XoeYR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC7XoeYR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC7XoeYR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC7XoeYR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC7XoeYR\App_KernelDevDebugContainer([
    'container.build_hash' => 'C7XoeYR',
    'container.build_id' => '931ffbb0',
    'container.build_time' => 1624379693,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC7XoeYR');
