<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'add_products' => [[], ['_controller' => 'App\\Controller\\ProductController::add'], [], [['text', '/api/product/add']], [], []],
    'get-all-products' => [[], ['_controller' => 'App\\Controller\\ProductController::getAll'], [], [['text', '/api/product/getAll']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\ProductController::index'], [], [['text', '/api']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
