<?php

namespace App\Tests\Entity;

use App\Entity\Product;
use PHPUnit\Framework\TestCase;

class ProductTest extends TestCase
{

    private Product $product;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->product = new Product();
    }
    public function testName(): void {
        $value = "nameTest";

        $response = $this->product->setName($value);
        $getName = $this->product->getName();

        self::assertInstanceOf(Product::class, $response);
        self::assertEquals($value, $getName);

    }
    public function testGetDescription(): void {
        $value = "testDescription";
        $response = $this->product->setDescription($value);
        $getDescription = $this->product->getDescription();

        self::assertInstanceOf(Product::class, $response);
        self::assertEquals($value, $getDescription);
    }
    public function testGetPrix(): void {
        $value = 1200;
        $response = $this->product->setPrix($value);
        $getPrix = $this->product->getPrix();

        self::assertInstanceOf(Product::class, $response);
        self::assertEquals($value, $getPrix);
    }
}
